# Site settings
title: "0x00jeff's blog"
description: 'reverse engineer wannabe'
keyword: 'ruby, rails, sinatra, javascript, vuejs, expressjs'
url: ''
baseurl: ''

# Navigation links
nav:
  home: '/'
  about: '/about.html'
  tags: '/tags.html'

# Footer
footer:
  since: 2019

# Author
author: '0x00jeff'
nickname: 'sometimes I go by uncle jeff'
bio: ''
avatar: 'assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true #always_true

# Comments
comments:
  disqus: true
  disqus_url: ''

# MathJax by Ray-Eldath
mathjax: false

# Share
social-share: false
social-share-items: ['twitter']

# theme color
theme-color: 'default' 

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'assets/img/banner.jpg'

# SNS settings 
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: 'https://github.com/0x00Jeff'
  twitter: 'https://twitter.com/Jeffsepticeye2'

# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', '_darkness', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
permalink: /:title.rb

# Plugins
plugins: [jekyll-paginate]
